[snowflake_account]
account = "VOLVOCARS-MANUFACTURINGANALYTICS"
authenticator = "externalbrowser"
role = "SELF_SERVICE_USER"
warehouse = "REPORTING"
database = "MANUFACTURING_ENTERPRISE_DATA_PRODUCTS"
schema = "BIS_ITEMS"